### ISSUE TITLE
Hand poses: 'Open', 'Closed' and 'Book'

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#116]
The game supports 3 poses for both the Left & Right hand: "Open," "Closed" and "Book." We should have Drauven hands for all three of these poses as well.

**Comment by Nexeron94** [comment]
I haven't encountered any character using the book poses in my playthrough. Can you give me some infos or examples how it looks on a human as well as a quick way to test it out myself so I can make fitting hands for them?

**Comment by BoldestDungeon** [comment]
An example is the Thnarrs Accordia, an artifact that you can get from the "Out of the Rain" event if you follow the stairs (or just cheat onto a character on the gear tab using dev mode).

The pose has the thumb going over the book, like this: 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/86335963/174613632-ec2fb20d-ee1a-46bf-940c-d255e056db36.png">

**Comment by Nexeron94** [comment]
> An example is the Thnarrs Accordia, an artifact that you can get from the "Out of the Rain" event if you follow the stairs (or just cheat onto a character on the gear tab using dev mode).
> 
> The pose has the thumb going over the book, like this: <img alt="image" width="365" src="https://user-images.githubusercontent.com/86335963/174613632-ec2fb20d-ee1a-46bf-940c-d255e056db36.png">

Ah I see, thanks! Is it only on the offhand or will the book pose also be required on the main hand?

**Comment by BoldestDungeon** [comment]
Currently it can only go to the offhand.  I think that _technically_ the main hand can possibly be told to do open/closed/book, but I don't think anything in the game actually uses those options for the right hand.  Let's just worry about the offhand for now.

**Comment by BoldestDungeon** [comment]
Also, apparently when holding a bow in your offhand your main hand gets set to its "open" pose! Discovered that today as I was deploying because we happened to have an open right hand in the assets for the Stump model.
