### ISSUE TITLE
Create new 'Tint' layers for clothing

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#123]
For some (even if not all) of the clothing layers, create grayscale 'tint' layers that can be layered over the base images and can be coloured using the 'Primary' or 'Secondary' tint colours.  This will allow our Drauven to have even more visual variety & customization.

**Comment by AnxiousLeopard** [comment]
Is this a duplication of #119? Sounds very similar. 
Theoretically sounds like an achievable, perhaps finicky, task once the individual clothing items are confirmed. 
Are we are sticking with the clothing existing in-game or are adjustments needed still for playability and weapons?

**Comment by AnxiousLeopard** [comment]
Just re-read, they are similar but slightly different but it might make sense to do the tasks at the same time if the process is the same.

**Comment by BoldestDungeon** [comment]
Aye, similar task but for a different set of layers. And yeah - if it makes sense to do the two at the same time, great!
The feathers one is a head detail, and probably makes sense to do after we have facial expressions figured out for the different heads, but this one I think could be taken any time since we have the clothing and the basic body poses already. I think, at least. @Nexeron94 might be able to correct me if I'm wrong. 🙂

**Comment by BoldestDungeon** [comment]
Closing this ticket as our last batch of art updates created layers on all the outfits that are more responsive to tinting than before.
