### ISSUE TITLE
Concussive blows bug

### ISSUE THREAD

**Issue by BipenTheBat** [BoldestDungeon/wildermyth-drauven-pcs#148]
Currently Concussive blows works on anything coded as attack roll in the game. That needs to be changed to only apply on melee attacks to balance the ability and to make it make more sense since you need to bonk to concuss someone not shoot them with a bow!

**Comment by HeroOfWind243** [comment]
See newest branch on ability bugfixes, now disables itself if attacking self or an ally, and only fires when the attack is tagged as melee.
