### ISSUE TITLE
Randomized extra details (e.g. beards, Drauven helmet) do not show up on overworld, only in battle.

### ISSUE THREAD

**Issue by justEthaniguess** [BoldestDungeon/wildermyth-drauven-pcs#15]
I'm really excited to see a mod for playable Drauven being made, so I've just decided to have a mess around with it in devMode and see how it currently works.

I triggered the event included in the mod for recruiting a Drauven Ranger/Haunt. I noticed that in the initial comic and the battle, the Drauven seemed to have a tendril-like beard/moustache and a Drauven helmet, however they both seemed to disappear when returning to the overworld map. They reappeared in the next battle, but disappeared after this was over again. I'm guessing that this is a bug with the hidden aspects granting these features?

Also, I apologise if I'm using this wrong, since this is my first time using GitHub. Please let me know if I'm submitting these wrong and I'll do my best to correct myself.

**Comment by justEthaniguess** [comment]
![screenshot_34](https://user-images.githubusercontent.com/104226556/164797909-d8d5ed2e-6276-4687-bad9-b313da0836e9.png)
![screenshot_35](https://user-images.githubusercontent.com/104226556/164797928-bf66139d-68c9-418e-bc4a-e3317d6aefa4.png)

Here are the in- and out-of-battle screenshots for my Haunt.

**Comment by BoldestDungeon** [comment]
Very weird - and yes, your report was perfect! Steps to reproduce + screenshots are definitely going to help. Thanks for taking a look and letting us know about this!

**Comment by justEthaniguess** [comment]
No problem. Glad to help! :)
