### ISSUE TITLE
Drauven details missing in legacy browser after booting the game

### ISSUE THREAD

**Issue by justEthaniguess** [BoldestDungeon/wildermyth-drauven-pcs#152]
## Description
This currently isn't possible without cheating yet since we cannot recruit a Drauv that started as a farmer, but it is something to consider when we do allow it and if we make it so that all classes start with random heads.

It appears as though Drauven with heads that do not match their class appear to reset in legacy. This is temporary however and they can be brought into a new campaign correctly. Loading the hero into the hero select screen for a legacy campaign seems to be a temporary fix as well.

## To Reproduce

1.  Use drauven_pc_init to change a recruitable farmer to a Drauven, until we get a Drauv with a non-standard head.
2.  Promote them to legacy.
3.  The head will change in the legacy browser.

## Screenshots (Optional)
![screenshot_529](https://user-images.githubusercontent.com/104226556/177052304-7d5e5396-fe6a-4403-a83c-a1d3944b1ad2.png)
![screenshot_530](https://user-images.githubusercontent.com/104226556/177052305-b283c7a0-48a6-4563-bad8-ad70fff206b0.png)
![screenshot_531](https://user-images.githubusercontent.com/104226556/177052307-021e1d56-cc76-4931-9979-b976dd75ad2d.png)

## Additional info (Optional)
Currently only have the one hero tested. I will try this out for other heads when I get the chance.

**Comment by justEthaniguess** [comment]
Further notes: It seems that this problem only occurs if you load the legacy browser right after booting the game. If you enter any campaign with the mod enabled, exit and head back to the legacy browser, the bug seems fixed for the most part. However, there are other things missing from the legacy browser as well as the proper heads, including arms and other head details.

**Comment by justEthaniguess** [comment]
![screenshot_533](https://user-images.githubusercontent.com/104226556/177058212-8ec03e99-44f2-4fde-9a94-109e84fd638c.png)
![screenshot_535](https://user-images.githubusercontent.com/104226556/177058188-7ac49cf2-a186-4abc-97b2-605b9e446e53.png)

**Comment by justEthaniguess** [comment]
[legacy.json.zip](https://github.com/BoldestDungeon/wildermyth-drauven-pcs/files/9881765/legacy.json.zip)

Got the legact here for you to check.

**Comment by BoldestDungeon** [comment]
@justEthaniguess - The legacy file seems to be working fine when I load it up on my end.  Can you try moving/renaming the legacy file, loading the game to hopefully clear any cache, quit, then restore the legacy file?

**Comment by BoldestDungeon** [comment]
This seems to have mostly resolved itself through other updates to the mod and/or base game.
