### ISSUE TITLE
Suggestion: Ability to Recruit Dravuen from Towns

### ISSUE THREAD

**Issue by justEthaniguess** [BoldestDungeon/wildermyth-drauven-pcs#16]
I would like the ability to create our own Drauven characters when recruiting from a town, on top of being able to recruit them from special events.

I was thinking if a good way to do it would be to have a pop-up event with choices after clicking the new recruit button, similar to those you get from choosing how to rebuild a hostile area after it has been cleared. You could then choose whether you want a human/legacy character, a Drauven, or to leave it to chance (with a high chance for creating a human for realism but a small chance of creating a Drauven). 

Clicking on Drauven would give another branching option to allow you to choose the class there and then, since Drauven faces do look completely different for each class. Then you'd be taken to the character creation screen for the Drauven after completing the first step of the recruitment task, where you customise personality, history, names, reroll head accessories to your liking and so on. Then you get an event for how and why the Drauven you customized joins your party and have to train them like any other new recruit.

I'm not sure of the feasibility of this since I don't know if it's possible to get characters to generate with the Drauven parts in the character creation screen, but I think it would be good for those who like creating their own heroes and would make creating and testing Drauven in campaigns a lot easier.

**Comment by BipenTheBat** [comment]
i think it might be possible if we replace the vanilla recruit event with our own one that has the option for you to choose a drauven recruit or a human

**Comment by justEthaniguess** [comment]
Sounds good. Thank you for the reply!
