### ISSUE TITLE
Update Event "Tell Me a Story" with Drauven Dialogue

### ISSUE THREAD

**Issue by Pikamew362** [BoldestDungeon/wildermyth-drauven-pcs#266]
## Comic Details
* **Name: Tell Me a Story** 
* **Type: ENCOUNTER_ARRIVE_AT_SITE**  

## What part of this comic should be updated?
Update drauven dialogue for when the tile threat is drauven, so it is more fitting.

## Screenshots (Optional)
![image](https://user-images.githubusercontent.com/115186645/214203365-377a9ada-9953-4eb2-a4f9-07969d373fbd.png)

**Comment by BoldestDungeon** [comment]
Note: This one gives us an opportunity to tell some Drauvish stories with the choices, so this one is a good candidate for updating more than the single word
