### ISSUE TITLE
Generic Deeven has hook aspects and no Monstrous tag, unlike other generic Drauven

### ISSUE THREAD

**Issue by justEthaniguess** [BoldestDungeon/wildermyth-drauven-pcs#32]
![screenshot_71](https://user-images.githubusercontent.com/104226556/166124836-3410bebb-edd2-440d-b906-9631934d6371.png)
![screenshot_72](https://user-images.githubusercontent.com/104226556/166124837-2ff304c6-0704-44b7-a204-59f11b106ae6.png)

Doesn't seem to be a serious issue, but I thought I'd mention it anyway since I noticed it from one of the DevTest events that gave me some of these guys to use temporarily.

It seems like the Deeven is missing the monstrous tag that other generic Drauven have and also has aspects for hook quests built in. I haven't noticed any gameplay issues caused by this (although it's curious how the Deeven now displays as the Citizen class, which I didn't know existed!) but I thought I might as well drop the bug quickly in here just in case.

**Comment by BoldestDungeon** [comment]
Nice find!

It's interesting that it's also getting "Hero," which is what I re-localized "Human" to - so it's somehow getting full human base stats from that as a bonus. That might also be what's causing 'Citizen' to show up on the ol' Snarky Snark
