### ISSUE TITLE
Skills project: Update blooded ferocity

### ISSUE THREAD

**Issue by psionusoid** [BoldestDungeon/wildermyth-drauven-pcs#401]
## What would you like to see added?

Update the drauven warrior Blooded Ferocity ability and its upgrade. At this time, it is likely to activate at inopportune times, causing its limited use(s) per battle to be wasted.

Potential ideas for improvements:
1. Have a cooldown instead of limited total number of uses
2. Triggered when taking damage (or just being targeted?) rather than when starting a turn with health missing
3. Add an effect that can prevent dropping to 0 health under certain conditions
4. Manual activation of the ability (controversial)
5. Damage buff while active (slightly controversial?)

**Comment by BoldestDungeon** [comment]
Closed by #402
