### ISSUE TITLE
Update Event "Hero Worship" with Drauven Dialogue

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#443]
## Comic Details
* **Name:** Hero Worship

## What part of this comic should be updated?
FoxySeven shares:
> also a slightly weird interaction here lol

## Screenshots (Optional)
![image](https://github.com/BoldestDungeon/wildermyth-drauven-pcs/assets/86335963/12c6b0dd-429a-419a-939c-b27e0248c429)

**Comment by justEthaniguess** [comment]
I think changing it to something along the lines of 'speculation that they weren't even from these Yondering Lands' would work, at least until someone makes a Thrixl PC mod lol. I'll work on this update now.
