### ISSUE TITLE
Randomized customization aspects do not show up in legacy

### ISSUE THREAD

**Issue by justEthaniguess** [BoldestDungeon/wildermyth-drauven-pcs#50]
![screenshot_111](https://user-images.githubusercontent.com/104226556/167204216-e1f90416-2544-4581-b74f-3a69e5509ca9.png)
![screenshot_112](https://user-images.githubusercontent.com/104226556/167204227-9a5341ff-23c9-401d-8118-b63c970d6109.png)

Randomized customization aspects (e.g. helmets, whiskers, feathers) do not seem to appear on Drauven after exporting them to the legacy. Thankfully, they do reappear if you use them as a legacy hero in a new campaign (both in combat and on the overworld), but they don't show up with the extra details in the legacy or on the main menu.

This seems very similar to the previous bug where these aspects only showed up in battle, although that bug has still been fixed.

**Comment by BoldestDungeon** [comment]
Note: Per Discord discussion, this one might be best solved by tapping into the human face customizations and keying our visuals off of that. (Head -> Horns, Hair -> Feathers, etc.)
