### ISSUE TITLE
Allow Drauven heroes to have Drauven children and Drauven relatives

### ISSUE THREAD

**Issue by justEthaniguess** [BoldestDungeon/wildermyth-drauven-pcs#51]
![screenshot_105](https://user-images.githubusercontent.com/104226556/167205014-6a464cec-c843-405f-b55a-cf34607244ab.png)

I've just decided to test this out to see what would happen and the two Drauven had a human child. It makes sense if they adopted, but I do think it would be nice for Drauven heroes to be able to have Drauven children (unless they're in a relationship with a human, then it could go either way).

![screenshot_93](https://user-images.githubusercontent.com/104226556/167206024-165d0e59-02b7-4402-b058-f173ee4c1396.png)

Also, on a somewhat related (ba-dum-tss) note, I have realised that some events in the game generate relatives for a hero, such as 'Family Business' and the 'Found Family' comic shown above. The relative is generated to look closely related to the hero in question. In the case of Found Family above, the 'parent' is supposed to also look similar to the hero, although they aren't actually related in this case. I do think it is funny for a human mistaking a Drauv for their child (unless they really did have a Drauven child) so I don't think it's a big deal for this event in particular, but I can imagine that it will be more confusing for events where the NPC is actually supposed to be a relative of the Drauven hero. I'm not sure if the mechanics for generating a relative is the same as for generating a child, but if it is it might be a chance to kill two birds with one stone?

**Comment by BoldestDungeon** [comment]
Note to whoever takes this one: It might be helpful to look at the "Legacy Children" mod to see what the author of that one did to override/replace the child generation. We could probably do something similar to forcefully apply the drauven theme.

Not sure if we can override the "Similar-to" relative part - we may need to go into each event one-by-one and do a test for whether the target has the drauven theme or not, and if so apply that theme (& name generation) to the relative.
