### ISSUE TITLE
Feature Request: Anchors (Auto-Generated)

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#621]
A new Comic Update Request has been made through Discord: 
[Anchors](https://discord.com/channels/968305036700549192/1250583286179168327)

_If this feature is accepted, please replace this auto-generated message with a proper summary of the task requirements._

**Comment by justEthaniguess** [comment]
This is a duplicate of an existing issue, so I'll close it.
