### ISSUE TITLE
Feature Request: What Danger Demands Campaign Intro (Auto-Generated)

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#622]
A new Comic Update Request has been made through Discord: 
[What Danger Demands Campaign Intro](https://discord.com/channels/968305036700549192/1252731488752111737)

_If this feature is accepted, please replace this auto-generated message with a proper summary of the task requirements._

**Comment by justEthaniguess** [comment]
Just pushed a pull request for this! I've updated all the comics except the initial What Danger Demands comic (which has been edited before) with new Drauven and Drauv-friendly text, especially in the event of having a Drauven threat in this campaign.
