### ISSUE TITLE
More dialogue in "The Abandoned Returns"

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#68]
## Comic Details
* **Name:** The Abandoned Returns
* **Type:** 
* **File Name** (_optional_): 

## What part of this comic should be updated?

Zel writes:

> First round of feedback...go!
> So, I'm thinking it might help the comic intro for when you find the abandoned again if you add an additional panel or two that talks about them walking through a deep forest (or something) and one of the heros says something like "haven't been in a forest this thick/dark/gloomy (or whatever) since we ran across that drauven child." Then they start talking about the child. It's not bad as it is, i just feel like this gives a little more context about why are they suddenly thinking about the Draven child all these years later.

**Comment by BoldestDungeon** [comment]
NB: Comic also looks weird if Hothead isn't present - maybe make the hothead role fill with `(200*drauvenSkeptic) + hothead` selection criteria?

**Comment by Pikamew362** [comment]
![image](https://user-images.githubusercontent.com/115186645/204927861-4092594e-8cf3-490c-93ed-25a44055cff8.png)

**Comment by BoldestDungeon** [comment]
Resolved with updated comic
