### ISSUE TITLE
Update Event "Emperor" with Drauven Dialogue

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#70]
## Comic Details
* **Name:** Emperor
* **Type:** Capstone/Generic campaign
* **File Name** (_optional_): 

## What part of this comic should be updated?

A Drauven character might have some interesting insight in this comic:
![image](https://user-images.githubusercontent.com/86335963/170307371-f1db198f-14c3-40d6-adb2-c1983eae3732.png)

**Comment by TausHaus** [comment]
there are a set of comics for this generic campaign story. they can be found in the editor as  
"genericcampaignplots_last_imperialPalace" 
we might want to edit multiple of them

**Comment by BoldestDungeon** [comment]
> we might want to edit multiple of them

Aye, agreed :)

**Comment by justEthaniguess** [comment]
I'm making some edits to these comics now. Done with the changes of the comic in the screenshot above and now working on the  other comics in this plot. I'll let you guys know when I've got some first drafts for this.
