### ISSUE TITLE
Update Event "The Abandoned" with MORE Drauven Dialogue

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#81]
## Comic Details
* **Name:** The Abandoned
* **Type:** 
* **File Name** (_optional_): 

## What part of this comic should be updated?

When a Drauv is filling in the slot for the Healer in The Abandoned, the dialogue should probably be a touch spicier

## Screenshots (Optional)
![image](https://user-images.githubusercontent.com/86335963/170623427-d6a9f9ba-d021-4b79-b585-eace9df55964.png)

**Comment by BoldestDungeon** [comment]
By this point in the comic the Drauven child has already been generated as an NPC, so the healer role can use the proper pronoun, too.

**Comment by Nexeron94** [comment]
I wonder if the hothead dialog can be changed as well if the healer is Drauven. Kind of weird when the hothead exclaims "its a drauven" and "it being a monster" while talking to one 😄 

Additionally, if the hothead is drauven too, maybe they would rather argument that the child has to learn surviving on its own. Or the hostility comes from the fact that they dont know which tribe the child belongs.

**Comment by justEthaniguess** [comment]
Currently, we are looking at restricting this event to only trigger if no Drauven exist in the company, just to avoid the moral issue that abandoning what is known to be a sapient child brings up. We are however going to look at providing other means of recruiting Drauven in the party when you already have one before we push this change.
